<a href="https://colab.research.google.com/github/nedokormysh/Stepik_DLS_basic/blob/week_6/%5Bhomework%5Dnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [ ]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.8301602  0.71860173 0.93570058 ... 0.25013665 0.0172426  0.33886209]
 [0.29130461 0.39537776 0.21390095 ... 0.07931937 0.38081105 0.3518201 ]
 [0.29997548 0.96517985 0.19931708 ... 0.09082606 0.65003133 0.58137891]
 ...
 [0.51813566 0.94439679 0.21640655 ... 0.63101114 0.85353044 0.14500526]
 [0.9662989  0.41442933 0.47324641 ... 0.43123483 0.03758928 0.24541787]
 [0.26565713 0.78832812 0.17399828 ... 0.35854756 0.76649798 0.95214919]]
[[0.8306739  0.07380346 0.64085807 ... 0.41076339 0.37370529 0.25277781]
 [0.02569054 0.81818272 0.66631207 ... 0.7767563  0.39630238 0.33232778]
 [0.68938085 0.50521631 0.90753539 ... 0.41092339 0.68241784 0.85473582]
 ...
 [0.75338312 0.56337311 0.86290733 ... 0.91749024 0.47868709 0.52483472]
 [0.23742983 0.61716416 0.00757247 ... 0.42677253 0.85267138 0.65177042]
 [0.10574712 0.60978905 0.34378945 ... 0.77150276 0.12291424 0.75681181]]


In [ ]:
b.T

array([[0.8306739 , 0.02569054, 0.68938085, ..., 0.75338312, 0.23742983,
        0.10574712],
       [0.07380346, 0.81818272, 0.50521631, ..., 0.56337311, 0.61716416,
        0.60978905],
       [0.64085807, 0.66631207, 0.90753539, ..., 0.86290733, 0.00757247,
        0.34378945],
       ...,
       [0.41076339, 0.7767563 , 0.41092339, ..., 0.91749024, 0.42677253,
        0.77150276],
       [0.37370529, 0.39630238, 0.68241784, ..., 0.47868709, 0.85267138,
        0.12291424],
       [0.25277781, 0.33232778, 0.85473582, ..., 0.52483472, 0.65177042,
        0.75681181]])

In [ ]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    pass

In [ ]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    pass

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

In [ ]:
def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param second: list of "size" lists, each contains "size" floats
    """

    result = []
    for i in range(len(a)):
      result.append([0 for i in range(len(b[0]))])

    length = len(a)

    #YOUR CODE: please do not use numpy
    for i in range(length):
      for j in range(length):
        for k in range(length):
          result[i][j] += first[i][k] * second[k][j]

    # result = sum([first * second for x, y in zip(first, second)])
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """
    

    #YOUR CODE: please use numpy

    result = first.dot(second)
    return result

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.4101096  0.15021243 0.79497719] [0.95409231 0.71415289 0.78734916]


In [ ]:
for x, y in zip(a, b):
  print(x * y)

0.3912824166547765
0.10727464326695044
0.6259246243845606


In [ ]:
sum([x * y for x, y in zip(a, b)])

1.1244816843062875

In [ ]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    # pass

    return sum([x * y for x, y in zip(a, b)])

In [ ]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    # pass

    return np.dot(a, b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 34 µs, sys: 4 µs, total: 38 µs
Wall time: 42 µs
CPU times: user 1.55 ms, sys: 0 ns, total: 1.55 ms
Wall time: 1.92 ms


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [ ]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass

    res = 0
    for i in range(len(a)):
      if a[i][i] % 2 == 0:
        res += a[i][i]
    
    return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 4, 6, 2, 9],
       [7, 9, 5, 7, 3],
       [2, 2, 1, 9, 2],
       [6, 6, 3, 1, 3],
       [6, 7, 4, 9, 1]])

In [ ]:
a.diagonal()

array([5, 9, 1, 1, 1])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 39 µs, sys: 5 µs, total: 44 µs
Wall time: 47.2 µs


0

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [ ]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass
    result = np.cumsum(A, axis=-1)

In [ ]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: user 72 µs, sys: 0 ns, total: 72 µs
Wall time: 76.1 µs


In [ ]:
A = sps.uniform.rvs(size=5) 
A

array([0.82902649, 0.17383158, 0.0599646 , 0.54256335, 0.20459852])

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [ ]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass
    X_= X.copy()
    X_[:, 1::2] = a
    X_[:, ::2] = np.power(X_[:, ::2], 3)
    X_ = X_[:, ::-1]

    return np.concatenate((X, X_), axis=1)

In [ ]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)
S2

CPU times: user 112 µs, sys: 15 µs, total: 127 µs
Wall time: 105 µs


array([[  1,   3,   5,   7,   9, 729,   5, 125,   5,   1]])

In [ ]:
X = np.array([[i for i in range(1, 10, 2)]])
X

array([[1, 3, 5, 7, 9]])

In [ ]:
X_ = X.copy()
X_[:, 1::2]=69
X_

array([[ 1, 69,  5, 69,  9]])

In [ ]:
X = np.array([[1,2,3,4,5], [1,2,3,4,5]])
# X = [[1, 3, 5, 7, 9]]

X_= X.copy()
# X_
X_[:, 1::2] = 69
X_[:, ::2] = np.power(X_[:, ::2], 3)
X_ = X_[:, ::-1]
np.concatenate((X, X_), axis=1)

array([[  1,   2,   3,   4,   5, 125,  69,  27,  69,   1],
       [  1,   2,   3,   4,   5, 125,  69,  27,  69,   1]])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass
    a_new = np.append([0], a)
    b = np.diff(a_new)
    c = np.nonzero(b)

    a_new = np.append(a_new, [0])

    b_new =  np.diff(a_new)
    c_new = np.nonzero(b_new)
    np.diff(c_new).ravel()
    result = (a[c], np.diff(c_new).ravel())
    return result

In [ ]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

x, num

CPU times: user 967 µs, sys: 0 ns, total: 967 µs
Wall time: 1.04 ms


(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))

In [ ]:
a = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

a_new = np.append([0], a) # добавляем 0 слева: array([0, 1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

b = np.diff(a_new) # array([ 1,  1,  0,  1,  0, -2,  0,  4,  0, -3,  1,  0])
c = np.nonzero(b) # (array([ 0,  1,  3,  5,  7,  9, 10]),)

a_new = np.append(a_new, [0]) # добавляем 0 справа: array([0, 1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3, 0])

# теперь повторяем все то что Вы делали

b_new =  np.diff(a_new) # array([ 1,  1,  0,  1,  0, -2,  0,  4,  0, -3,  1,  0, -3]) 
c_new = np.nonzero(b_new) # (array([ 0,  1,  3,  5,  7,  9, 10, 12]),) сравните с массивом c (теперь мы учли крайние элементы)
np.diff(c_new).ravel() # array([1, 2, 2, 2, 2, 1, 2])

# или как это будет выглядеть в ответе:

result = (a[c], np.diff(c_new)) # (array([1, 2, 3, 1, 5, 2, 3]), array([[1, 2, 2, 2, 2, 1, 2]]))

# забыл .ravel() :
result = (a[c], np.diff(c_new).ravel()) # (array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))